// The throw statement defines a custom error.

// Normal Function 

function Mulitplication(a , b ){
    return a * b
}
console.log(Mulitplication(4 , 5))

// Arrow function 

let division = (a ,b) => a / b ;

console.log(division(20,5))